const transactionIdMapper = Object.freeze({
  Login: 0,
  Signup: 1,
  RefreshToken: 2,
  RequestPasswordChange: 3,
  ValidatePasswordChangeCode: 4,
  ChangePassword: 5,
  ConfirmAccount: 6,
  GetUserData: 7,
  ValidateSession: 8,
  InactivateSession: 9,
  UserHasPermission: 10,
  ProcessCreateReport: 11,
  GenerateCSV: 12,
  GenerateHTML: 13,
  GenerateXLSX: 14,
  GeneratePDF: 15,
  GenerateDOCX: 16,
  GetAllReports: 17,
  GetReportById: 18,
  CreateReports: 19,
  CreateTemplate: 20,
  UpdateTemplate: 21,
  DeactivateTemplate: 22,
  DeleteTemplate: 23,
  GetAllLogs: 24,
  GetLogById: 25,
  DownloadLogs: 26,
  ClearLogs: 27,
  GetAllAuditLogs: 28,
  GetAuditByIdLogs: 29,
  DownloadAuditLogs: 30,
  GetAllUsers: 31,
  GetUserById: 32,
  DashboardData: 33,
  GetAllTemplates: 34,
});

module.exports = transactionIdMapper;
