const transactionIdMapper = Object.freeze({
  Login: 0,
  Signup: 1,
  RecoverPassword: 2,
  ResetPassword: 3,
  ConfirmAccount: 4,
  RefreshToken: 5,
  InactivateSession: 6,
  UserHasPermission: 7,
  ValidateSession: 8,
  ProcessCreateReport: 9,
  GenerateCSV: 10,
  GenerateHTML: 11,
  GenerateXLSX: 12,
  GeneratePDF: 13,
  GenerateDOCX: 14,
  GetAllReports: 15,
  GetReportById: 16,
  CreateReports: 17,
  CreateTemplate: 18,
  UpdateTemplate: 19,
  DeactivateTemplate: 20,
  DeleteTemplate: 21,
  GetAllLogs: 22,
  GetLogById: 23,
  DownloadLogs: 24,
  ClearLogs: 25,
  GetAllAuditLogs: 26,
  GetAuditByIdLogs: 27,
  DownloadAuditLogs: 28,
});

module.exports = transactionIdMapper;
