INSERT INTO roles (name) VALUES 
  ('OWNER'), 
  ('ADMINISTRATOR'),
  ('USER');

INSERT INTO objects (name) VALUES 
  ('AuthenticationService'), 
  ('AuthorizationService'), 
  ('ReportsService'),
  ('TemplateService'),
  ('LogsService'),
  ('AuditService'),
  ('UserService');

INSERT INTO methods (name, object_id) VALUES 
  ('Login', 1), 
  ('Signup', 1), 
  ('RefreshToken', 1),
  ('RequestPasswordChange', 1),
  ('ValidatePasswordChangeCode', 1),
  ('ChangePassword', 1),
  ('ConfirmAccount', 1),
  ('GetUserData', 1),
  ('ValidateSession', 2),
  ('InactivateSession', 1),
  ('UserHasPermission', 2),
  ('ProcessCreateReport', 3),
  ('GenerateCSV', 3),
  ('GenerateHTML', 3),
  ('GenerateXLSX', 3),
  ('GeneratePDF', 3),
  ('GenerateDOCX', 3),
  ('GetAllReports', 3),
  ('GetReportById', 3),
  ('CreateReports', 3),
  ('CreateTemplate', 4),
  ('UpdateTemplate', 4),
  ('DeactivateTemplate', 4),
  ('DeleteTemplate', 4),
  ('GetAllLogs', 5),
  ('GetLogById', 5),
  ('DownloadLogs', 5),
  ('ClearLogs', 5),
  ('GetAllAuditLogs', 6),
  ('GetAuditByIdLogs', 6),
  ('DownloadAuditLogs', 6),
  ('GetAllUsers', 7),
  ('GetUserById', 7),
  ('DashboardData', 3),
  ('GetAllTemplates', 4),
  ('UpdateUser', 7),
  ('DeleteUser', 7),
  ('ChangeUserPassword', 1);

INSERT INTO role_methods (role_id, method_id) SELECT 1, id FROM methods;

INSERT INTO role_methods (role_id, method_id) VALUES
  (2, 1),
  (2, 2),
  (2, 3),
  (2, 4),
  (2, 5),
  (2, 6),
  (2, 7),
  (2, 8),
  (2, 9),
  (2, 10),
  (2, 11),
  (2, 12),
  (2, 13),
  (2, 14),
  (2, 15),
  (2, 16),
  (2, 17),
  (2, 18),
  (2, 19),
  (2, 20),
  (2, 21),
  (2, 22),
  (2, 29),
  (2, 30),
  (2, 31),
  (2, 32),
  (2, 33),
  (2, 34),
  (2, 35),
  (2, 36),
  (2, 37),
  (2, 38),
  (3, 39);

INSERT INTO role_methods (role_id, method_id) VALUES
  (3, 1),
  (3, 2),
  (3, 3),
  (3, 4),
  (3, 5),
  (3, 6),
  (3, 7),
  (3, 8),
  (3, 9),
  (3, 10),
  (3, 11),
  (3, 12),
  (3, 13),
  (3, 14),
  (3, 15),
  (3, 16),
  (3, 17),
  (3, 18),
  (3, 19),
  (3, 20),
  (3, 34),
  (3, 36),
  (3, 37),
  (3, 38),
  (3, 39);

INSERT INTO report_status (name) VALUES 
  ('COMPLETED'), 
  ('PENDING'), 
  ('GENERATING'), 
  ('ERROR'), 
  ('CANCELLED'), 
  ('FAILED');

INSERT INTO template_types (name) VALUES
  ('PDF'),
  ('HTML'),
  ('DOCX');


